# Main configuration file for mkdocs generation of BIGTREETECH.org website

# Note that the build-translations.sh script expects a certain file
# layout.  See that script and the README file for more details.

# Site and directory configuration
site_name: BIGTREETECH documentation
repo_url: https://github.com/z1996xm/BIGTREETECH
repo_name: z1996xm/BIGTREETECH
edit_uri: blob/main/docs/
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

# Custom markdown dialect settings
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  search:
    lang: en
  mkdocs-simple-hooks:
    hooks:
      on_page_markdown: "docs._biqumkdocs.mkdocs_hooks:transform"
  exclude:
    glob: "README.md"

# Website layout configuration (using mkdocs-material theme)
theme:
  name: material
  custom_dir: material/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: img/BQ-BIQU.svg
  favicon: img/favicon.ico  
  icon:
    repo: fontawesome/brands/github
    alternate: material/web
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
extra_css:
  - _biqumkdocs/css/extra.css
  - _biqumkdocs/css/zoom.css
# Site usage statistics
# extra:
#   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#site-search-tracking
#   analytics:
#     provider: google
#     property: UA-138371409-1
#   # Language Selection
#   alternate:
#     - name: English
#       link: /
#       lang: en
    # Alternate language links automatically added here

# Navigation hierarchy (this should mimic the layout of Overview.md)
# nav:
#   - BTT documentation.md
#   - Motherboards:
#     - SKR Series:
#       - SKR MINI E3.md
#     - Octopus Series:
#       - Octopus.md
#       - Octopus Pro.md
#       - Octopus MAX EZ.md
#     - Manta Series:
#       - M4P.md
#       - M5P.md
#       - M8P.md
#     - EBB Series:
#       - EBB 36 CAN.md
#       - EBB 42 CAN.md
#       - EBB 2240 2209 CAN.md
#       - EBB 2240 2209 CAN RP2024.md
#       - U2C.md
#   - IOT:
#     - CB1.md
#     - PI4B.md
#     - PAD7.md
#     - KNOMI.md
#   - Displays:
#     - TFT43-DIP.md
#     - TFT35 E3.md
#     - TFT35.md
#     - TFT24.md
#     - TFT35 SPI.md
#     - HDMI5.md
#     - HDMI7.md
#   - Motor Drives:
#     - TMC Series:
#       - TMC2130.md
#       - TMC5160.md
#       - TMC2209.md
#       - TMC2208.md
#       - Tutorials.md
#     - EZ Series:
#       - EZ2130.md
#       - EZ2208.md
#       - EZ2225.md
#       - EZ2226.md
#       - EZ5160 Pro.md
#       - EZDriver Connector.md
#       - EZ2209.md
#       - EZ2240.md
#       - EZ31865.md
#   - Software Tutorials:
#     - Software Configuration.md
#     - Software Installation.md
#     - EBB Series.md
#   - BIQU documentation.md
#   - Extruders:
#     - Extruders.md
#   - Hotends:
#     - Hotends.md
#   - Sensor modules:
#     - Sensor modules.md
#   - Printers:
#     - Printers.md
#   - Panda series:
#     - Panda series.md

nav:
  - Home: Printers.md
  - BTT Series: 
    - Extruders: Extruders.md
    - Hotends: Hotends.md
  - BIQU Series: 
    - Motherboards:
      - SKR Series: SKR MINI E3.md
  - ABOUT: Panda series.md

